version: "3" # Compose.yml 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  docker-activemq: # 서비스 명
    image: rmohr/activemq:5.15.9 # 사용할 이미지
    container_name: docker-activemq # 컨테이너 이름 설정
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://boot2docker:8161/admin (admin:admin)
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
    volumes:
      - ~/docker/activemq:/data/activemq