version: "3" # Compose.yml 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  docker-elasticsearch: # 서비스 명
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2 # 사용할 이미지
    container_name: docker-elasticsearch # 컨테이너 이름 설정
    ports:
      - "9200:9200" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/docker/mysql:/usr/share/elasticsearch/data # -v 옵션 ( 디렉토리 마운트 설정 )