version: "3" # Compose.yml 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  docker-activemq: # 서비스 명
    image: rabbitmq:3.13.7-management # 사용할 이미지
    container_name: docker-rabbitmq-3.13.7 # 컨테이너 이름 설정
    ports:
      - "15672:15672" # broker (admin:adminactivemq)(amq:amq)
      - "5672:5672"   # web    http://boot2docker:8161/admin (admin:admin)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ~/docker/rabbitmq-3.13.7:/var/lib/rabbitmq